devices:
  depo:
    s_positions:
      full_down: 200
      full_up: 426
    vol_deg_map:
      0.0: 562
      0.143: 696
      0.223: 758
      0.314: 828
      0.41: 909
      0.513: 988
      0.602: 1061
    x_offset: -66
    y_offset: -195
  pH:
    pH_positions:
      full_down: -167
      full_up: -649
    verbose: true
    x_offset: 0
    y_offset: 0
global:
  pi1_address: 192.168.0.2
  pi2_address: 192.168.0.3
stage:
  aux_loc_map:
    acid:
    - -1260
    - -125
    base:
    - -1260
    - -655
    clean:
    - -1108
    - -452
  cell_loc_map: C:\Users\logan\Documents\Spring 2023\Research\LEGOLAS with Camera\LEGOLAS
    Files\cell_map.pkl
  home_x_offset: -100
  home_y_offset: -100
